Fix isPublic check for licenses array
vercel/pkg pull request #1140
Opened 2021-04-20 17:57 UTC by Hypfer

As it turns out, not including bytecode is broken for modules that have a licenses array in their package.json.

One example of this is `utils-merge` which is a dependency of `express`.

Without this check, `license` will become undefined since there's no `type` property on that array.
This causes the module to be listed as non-public which means that it doesn't get included as CONTENT
That in turn triggers the exception when building without bytecode.

Anyways, this was not fun to debug.

This fixes #1139

2021-04-20 18:16 UTC, Hypfer commented
Actually, this doesn't fix the issue #1139, because the module `uid2`, which is used in the example there, features no license at all and will therefore always be listed as private.

It doesn't matter for my main project and this still fixes a bug, however I suppose it would make sense to hide the `isPublic` check behind some kind of flag, so that it's just used by people that actually need it and not breaks foss projects for absolutely no reason

2021-04-21 06:12 UTC, robertsLando requested changes
@Hypfer thanks for this fix, could you also mention this flag in docs please?

2021-04-21 15:41 UTC, Hypfer commented
Done

2021-04-22 08:39 UTC, robertsLando approved these changes
LGTM

2021-04-22 08:40 UTC, merged