feature: allow macOS code signing by including payload in str table
vercel/pkg pull request #1164
Opened 2021-05-05 11:43 UTC by jesec

Inspired by dotnet/runtime#46558 .

Test: manual, Apple M1 (with [mandatory code signing requirement](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes))

```zsh
 Θ pkg -t node14-mac-arm64 . 
> pkg@5.1.0
> Warning Cannot resolve 'config'
  /Users/jc/Sources/pkg/lib-es5/index.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot find module 'internal/util' from '/Users/jc/Sources/pkg/prelude'  in /Users/jc/Sources/pkg/prelude/bootstrap.js
> Warning Cannot find module 'internal/module' from '/Users/jc/Sources/pkg/prelude'  in /Users/jc/Sources/pkg/prelude/bootstrap.js
> Warning Cannot find module 'internal/modules/cjs/helpers' from '/Users/jc/Sources/pkg/prelude'  in /Users/jc/Sources/pkg/prelude/bootstrap.js

 [~/S/pkg] [G pr/macos-sign 00a3e2e ?] [Ad-hoc sign the fabricator binary temporarily to generate bytecode on macOS]
 Θ lipo -info pkg
Non-fat file: pkg is architecture: arm64

 [~/S/pkg] [G pr/macos-sign 00a3e2e ?] [Ad-hoc sign the fabricator binary temporarily to generate bytecode on macOS]
 Θ ./pkg
> pkg@5.1.0
...

 [~/S/pkg] [G pr/macos-sign 00a3e2e ?] [Ad-hoc sign the fabricator binary temporarily to generate bytecode on macOS]
 Θ codesign --verify ./pkg && echo $?
0
```

Bug: #66, #128, #1023

2021-05-05 12:20 UTC, robertsLando requested changes
Looks good from a code side, BTW tests are broken.

2021-05-05 14:07 UTC, jesec commented
> Looks good from a code side, BTW tests are broken.

I think the tests are flaky, and they only fail with Node 16. I will run them again.

2021-05-05 14:52 UTC, jesec commented
I rerun the tests on the HEAD (https://github.com/vercel/pkg/commit/ea7d72bc2052e717bd89ab1714d5894dd5e9bfa7), and they fail. Clearly our tests don't work with Node 16.1.

2021-05-05 15:17 UTC, robertsLando commented
Could you take a look at them?

2021-05-07 07:08 UTC, jesec commented
> Could you take a look at them?

Apprently nodejs/node@9c06103a4f2dcf4ef2bb1e732332008cd93378fd is the commit that breaks the tests.

2021-05-10 07:05 UTC, robertsLando approved these changes
LGTM. Good job :)

2021-05-10 07:56 UTC, merged

2023-06-20 20:21 UTC, tmm1 commented
@jesec any idea how this could be extended to support fat binaries? https://github.com/vercel/pkg/issues/1597