Prerequisite changes of feature/compression
vercel/pkg pull request #1204
Opened 2021-06-02 06:12 UTC by jesec

Compression change (#1200) is giant. It would be easier for us to split, review and merge the related changes first.

2021-06-02 20:10 UTC, erossignon requested changes

2021-06-02 20:10 UTC, erossignon commented on prelude/bootstrap.js
> +          require('fs').exists(path_, (exists) => {
=> fs.exists

2021-06-02 20:10 UTC, erossignon commented on prelude/bootstrap.js
>      Object.defineProperty(require('fs').exists, custom, {
require('fs') => fs

2021-06-02 20:10 UTC, erossignon commented on prelude/bootstrap.js
> -      if (NODE_VERSION_MAJOR === 0) {
Shall this go to a different commit ?

2021-06-02 20:10 UTC, erossignon commented on prelude/bootstrap.js
>    return require('util').types.isRegExp(val);
const {isRegExp} = require('util').types;

2021-06-02 20:10 UTC, erossignon commented on prelude/bootstrap.js
> -    if (NODE_VERSION_MAJOR <= 7) {
Shall we move to a differnt commit ? this is changing logic

2021-06-03 05:16 UTC, erossignon requested changes
I see a few 'var' left in boostrap.js that we could get rid off while we are here.

May be we could replace `path_`  with either `filename`  `pathname` or `foldername` as appropriate.

2021-06-03 05:55 UTC, jesec commented
> I see a few 'var' left in boostrap.js that we could get rid off while we are here.
> 
> May be we could replace `path_` with either `filename` `pathname` or `foldername` as appropriate.

Done. 

I think `path` is best fit here.

2021-06-03 06:25 UTC, robertsLando approved these changes

2021-06-03 06:26 UTC, erossignon approved these changes

2021-06-03 07:55 UTC, merged