adding --static option
vercel/pkg pull request #1222
Opened 2021-06-16 21:12 UTC by dimitribocquet

Based on https://github.com/vercel/pkg/issues/1221, I've added the `--static` option to override the host platform value, and force to use linuxstatic binaries.

I am far from sure to do it well, so feel free to improve it! 😅

2021-06-17 06:16 UTC, robertsLando approved these changes
LGTM

2021-06-17 06:17 UTC, jesec requested changes
-2. See my comments in the linked issue.

2021-06-17 06:26 UTC, robertsLando commented
Yep I have read it after I saw the PR. Got it I just would like to know what's the alternative to this as this seems that is working for the user

2021-07-06 11:52 UTC, jesec commented
Per the comments, I will close the PR. 

Note again that support for `armv7` is best-effort basis WITHOUT semver guarantees.

2021-07-06 11:52 UTC, closed without merging