test: add esm module test
vercel/pkg pull request #1323
Opened 2021-09-30 13:16 UTC by robertsLando

Ref #1291

2021-09-30 15:17 UTC, jesec requested changes
There is a (huge) binary in the commit.

2021-09-30 15:36 UTC, robertsLando commented
Sorry the test has failed and i forgot to delete it, when it works the vacoom automatically removes it

2021-10-01 03:36 UTC, jesec commented
> Sorry the test has fails and i forgot to delete it, when it works the vacoom automatically removes it.
> 
> Just to be clear tests will not pass as this is not a fix to #1291 but it just reproduce the problem, I tried to fix it without success. Do you have any clue what's not working?

#782 

We have no support for ES6 modules yet. The walker can't parse the dependencies and include them in the payload.

2021-10-01 06:16 UTC, robertsLando commented
The strange thing is that the detector actually identifies `import` statements: https://github.com/vercel/pkg/blob/59125d1820cdb380f3f592604bcfd7c017495e77/lib/detector.ts#L258

Also in latest ncc updates now it outputs esm modules so it's not a solution at all. I think we need to add a support to esm modules as with node 14+ them are supported. If you could point me on the changes needed I could try to fix this.

2021-10-06 07:51 UTC, robertsLando commented
@jesec news here?

2021-11-10 10:44 UTC, robertsLando commented
This could be a starting point: https://github.com/vitejs/vite/pull/5593

2021-11-10 11:26 UTC, jesec commented
Our use case is considerably more complicated. `enhanced-resolve` is nowhere near to a drop-in replacement for `resolve` in our case. 

We would have to study the APIs of the `enhanced-resolve` and rewrite our logics.

2021-11-10 12:56 UTC, robertsLando commented
> We would have to study the APIs of the enhanced-resolve and rewrite our logics.

I agree, in my tests I was just tring to see what happened using that as a separete tool then the plan it's to completely replace resolve. I think this issue should be the top in our todos, do you want to do some tries? Test is already setted up

2022-01-21 20:07 UTC, hcldan commented
I have been using es6 in my projects, but before I run pkg I transpile them to commonjs.  This seems to work well.  It would be great if this support landed natively or if you just built in the transpiling part so I didn't have to.

2022-01-24 08:30 UTC, robertsLando commented
> I transpile them to commonjs

Do you use webpack for this?

2022-01-24 15:35 UTC, hcldan commented
rollup worked really well, as I don't need the features of webpack, I just need my modules to be cjs in the end.

package.json
```json
{
  "scripts": {
     "build": "npm-run-all build:*",
     "build:1": "rimraf dist",
     "build:2": "mkdirp dist",
     "build:4": "rollup index.js -o dist/built.js --format cjs",
     "build:5": "pkg dist/built.js --targets linux,win --out-path dist"
  }
}
````

2022-01-24 15:36 UTC, hcldan commented
sourcemaps are a pain... so native support would be fantastic

2022-01-31 09:55 UTC, rightaway commented
I can help to test when it is ready.

2022-03-03 17:56 UTC, RUGMJ7443 commented
are there any updates or workarounds for this? I really need to distrabute my package ASAP

2022-03-03 18:22 UTC, kamack38 commented
> are there any updates or workarounds for this? I really need to distrabute my package ASAP

You can use `caxa`, because they are supporting ESM.

2022-03-04 16:02 UTC, hcldan commented
I've commented above for a decent workaround that I'm using

rollup can be configured to transpile and bundle all es modules in a file and defer all commonjs modules to the default require.
```

  "scripts": {
    "test": "npm-run-all test:*",
    "test:1": "eslint",
    "test:2": "NODE_OPTIONS=--experimental-vm-modules npx jest",
    "start": "cross-env node .",
    "build": "npm-run-all build:*",
    "build:1": "rimraf dist",
    "build:2": "mkdirp dist",
    "build:4": "rollup --config rollup.config.js",
    "build:5": "pkg dist/nwsp.js --targets linux,win --out-path dist"
  },
```

rollup.config.js
```
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  input: 'index.js',
  output: {
    file: 'dist/nwsp.js',
    format: 'cjs',
  },
  plugins: [
    nodeResolve({
      modulesOnly: true,
    }),
  ],
};
```

There are tons of options, look them over.  This gives you one big file with all es5 turned into commonjs.
Only big drawbacks here are complexity (it would be nice if this all just worked) and sourcemap support.
Rollup can output sourcemaps (even inline) but I cant get stacks reported by node to use that info.

2022-04-22 12:29 UTC, gaby commented
Any updates on this feature?

2022-05-14 22:20 UTC, rightaway commented
Would also like to know what the plans are with ESM modules support. Some dependencies like https://github.com/sindresorhus/got only work with ESM modules now and encourage switching (https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

The options are to stay on older versions of dependencies or to stop using pkg but it's better if we don't have to do either.

2022-06-20 06:43 UTC, robertsLando commented
This PR doesn't fixes this, @jesec has a working implementation but not finished yet and I dunno if there is any ETA on it

2022-09-19 00:29 UTC, gaby commented
Any reason why stale bot is trying to close PR's?

2022-09-19 11:21 UTC, CleyFaye commented
> Any reason why stale bot is trying to close PR's?

I'd say it's

> because it has been open 90 days with no activity

2022-09-25 21:10 UTC, angrymouse commented
Any updates on it?

2022-11-04 17:42 UTC, edosrecki commented
Any news at all?

2023-01-31 23:41 UTC, cspotcode commented
I think there is another issue here: even if the files are bundled into the virtual filesystem, it cannot be executed.  I'm guessing node's ESM resolver does not use the patched filesystem.

For example, you can bundle an ESM file alongside an CJS file, using the CJS file as entrypoint.  Then run stuff in the CJS file that looks vaguely like this:

```
// entrypoint.cjs:
// Prove that the file exists in VFS
console.log(fs.readdirSync('/snapshot'));
console.log(fs.readFileSync('/snapshot/bin.mjs'));
// But import fails
import('/snapshot/bin.mjs');
```

Gives a cryptic error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/snapshot/bin.mjs' imported from /snapshot/entrypoint.cjs
Did you mean to import /snapshot/bin.mjs?
```

Looking closely at that error, it says i cannot find the module, then it suggests exactly the same path.  I bet the suggestion comes from different code which is using the VFS.

2023-02-01 07:15 UTC, robertsLando commented
Unfortunately I have no clue about how to actually implement such feature, I would need some support on this

2023-04-06 00:41 UTC, Haringat commented
@robertsLando Perhaps you could create a custom loader that uses the virtual filesystem.
Here are some example implementations from the node docs: https://nodejs.org/dist/latest-v19.x/docs/api/esm.html#loaders

2023-04-07 13:48 UTC, robertsLando commented
@Haringat Thanks for your suggestion, BTW I don't think that would solve the issue, right now the problem is we don't have a way to resolve the modules used with esm, enhanced resolve should solve this issue but I have no clue how to make it work

2023-04-07 15:56 UTC, Haringat commented
@robertsLando But with the loader you can specify a custom resolve hook to do just that. It gets the URL it is supposed to resolve and the URL of the importing module.

2023-04-07 16:17 UTC, robertsLando commented
It would not work for dynamically loaded modules I think? I mean an async import for example will not be catched by it on startup

2023-04-07 19:06 UTC, Haringat commented
@robertsLando I just tested it with an HTTP/HTTPS loader and it was also invoked for a dynamic import.

2023-04-08 09:28 UTC, robertsLando commented
The problem is different here, we actually don't run a file with node to detect it's dependencies, we start from the entrypoint file and from that we recursively resolve all modules using "resolve" npm module, to detect them we simply use regex to find require/import statements in the files. Your suggestion so would not work in this case at is requires to run the entrypoint file, also there is no way to know how to trigger dynamic import in that way.

2023-10-15 00:23 UTC, closed without merging