fix broken tests on node 12; latest pnpm requires node >= 14.19
vercel/pkg pull request #1613
Opened 2022-05-03 12:21 UTC by kldzj

Tests on node 12 are failing because pnpm requires `node >= 14.19`.

2022-05-03 12:28 UTC, robertsLando approved these changes

2022-05-03 12:31 UTC, robertsLando requested changes

2022-05-03 12:31 UTC, robertsLando commented on test/utils.js
> +    console.log(`skiping test as it requires nodejs >= ${need} and got`, got);
```suggestion
    console.log(`skiping test as it requires nodejs >= ${need} and got ${got}`);
```

2022-05-03 12:53 UTC, robertsLando approved these changes

2022-05-05 04:57 UTC, jesec approved these changes

2022-05-05 04:58 UTC, merged