Workaround issue https://github.com/vercel/pkg/issues/1356
vercel/pkg pull request #1647
Opened 2022-05-31 10:19 UTC by orgrimarr

I find a simple work around for issue https://github.com/vercel/pkg/issues/1356

Setting a var env seems to work
```js
{
    env: {
        PKG_EXECPATH: 'PKG_INVOKE_SELF'
    }
}
```

```js
if (opts.env.PKG_EXECPATH === 'PKG_INVOKE_SELF') return;
```

@robertsLando  What do you think about this fix ?

2022-05-31 11:42 UTC, robertsLando reviewed
Instead of using an env var I suggest to auto-detect the spawn of itself in `childProcess.spawn` / `childProcess.spawnSync` calls, it makes more sense. Also if you want to test locally just run the single test you want not all the others. You pushed a huge pnpm-loc.yaml file, remove it

2022-05-31 11:43 UTC, robertsLando requested changes
Instead of using an env var I suggest to auto-detect the spawn of itself in `childProcess.spawn` / `childProcess.spawnSync` calls, it makes more sense. Also if you want to test locally just run the single test you want not all the others. You pushed a huge pnpm-loc.yaml file, remove it

2022-05-31 15:15 UTC, robertsLando requested changes

2022-05-31 15:15 UTC, robertsLando commented on .gitignore
> +*.bak
remove changes to this file

2022-05-31 15:16 UTC, robertsLando commented
Also fix lint issues please

2022-05-31 15:58 UTC, orgrimarr commented on .gitignore
> +*.bak
Should be fixed now

2022-06-01 06:24 UTC, robertsLando requested changes
A test is still failing

2022-06-01 13:42 UTC, robertsLando commented
Ok

2022-09-06 00:27 UTC, closed without merging

2022-10-26 14:50 UTC, lamualfa commented
This is great. Please merge it.