feat: use native node fs
vercel/pkg pull request #1763
Opened 2022-09-20 04:44 UTC by ignatiusmb

There's still a test case where it requires `fs-extra`, so I'm not sure if we can completely remove the package, but at least we can move it out of the dependency tree.

2022-09-20 07:01 UTC, robertsLando requested changes
I'm not sure about this changes. You have replaced lot async methods with sync ones, also fs-extra doesn't create so much overhead as it uses fs internally, it just extends it

2022-09-20 07:31 UTC, ignatiusmb commented
The rationale for replacing those async methods is because it's immediately `await`-ed and used — e.g., it's executed as `(await asyncThing()).anotherSyncMethod()`. I find that using synchronous methods for these operations a bit simpler and easier to read unless we need to do multiple things simultaneously.

> fs-extra doesn't create so much overhead as it uses fs internally, it just extends it

For this, I think it's more of a reason to not have it as a dependency, especially when we can already do the things we need with node's fs module.

Another reason is also to reduce and minimize dependencies as much as possible, recent survey shows that [managing dependencies is one of the biggest pain points when working with JS](https://2021.stateofjs.com/en-US/opinions/#js_pain_points_wins). Generally speaking, I think the less dependencies any project has, the better the experience would be, both for the maintainers and the users.

2022-09-20 07:44 UTC, ignatiusmb commented
Please let me know if you prefer to keep the async methods, I'll address them and make the changes.

2022-09-26 07:02 UTC, robertsLando approved these changes

2022-10-03 07:19 UTC, robertsLando commented
@jesec feel free to merge if it looks good to you

2023-02-27 06:50 UTC, ignatiusmb commented
What's left to do?

2023-02-27 11:15 UTC, robertsLando requested changes

2023-02-27 11:15 UTC, robertsLando commented on lib/chmod.ts
> +import { promises as fs } from 'fs';
```suggestion
import fs from 'fs/promises';
```

?

2023-02-27 11:15 UTC, robertsLando commented on lib/walker.ts
> +import { promises as fs } from 'fs';
```suggestion
import fs from 'fs/promises';
```

2023-02-28 18:43 UTC, ignatiusmb commented
@robertsLando ES6 `fs/promises` import won't work with Node v12 (https://stackoverflow.com/a/70042193).

2023-05-15 13:39 UTC, pcnate commented
> @robertsLando ES6 `fs/promises` import won't work with Node v12 (https://stackoverflow.com/a/70042193).

NodeJS 14.x is reaching the end of its LTS support. I doubt that 12.x should still be considered.

2023-08-20 00:21 UTC, closed without merging