chore: separate lint workflow
vercel/pkg pull request #1768
Opened 2022-09-22 05:59 UTC by ignatiusmb

We may not know if CI actually failed or flaked out at a glance, separating lint into its own job would make it easier to read.

2022-09-22 06:05 UTC, ignatiusmb commented
Whoops, I changed the matrix version array to just numbers because we only care about the major versions and it's recommended to use this format instead. Are the 'required' checks manually assigned to "12.x" and "14.x" strings or something, is there some way to adjust those?

2022-09-22 06:10 UTC, ignatiusmb commented
While we're here, we should replace them (the checks) with v16 — arguably v18 too — as v12 is already EOL and v14 is nearing to EOL in 7 months.

2022-09-22 06:50 UTC, robertsLando commented
> Are the 'required' checks manually assigned to "12.x" and "14.x" strings or something, is there some way to adjust those?

Unfortunally yes and I don't have the privileges to change this

2022-09-22 06:51 UTC, robertsLando commented
> While we're here, we should replace them (the checks) with v16 — arguably v18 too — as v12 is already EOL and v14 is nearing to EOL in 7 months.

We also support some EOL versions

2022-09-22 07:44 UTC, ignatiusmb commented
> We also support some EOL versions

Could you please explain why?

2022-09-22 07:46 UTC, ignatiusmb commented
> and I don't have the privileges to change this

Don't mean to be rude, but do we know anyone we can or should mention for this?

2022-09-24 15:51 UTC, leerob commented
<img width="807" alt="CleanShot 2022-09-24 at 10 50 54@2x" src="https://user-images.githubusercontent.com/9113740/192107155-5f95f222-0e84-4c29-9afd-1ea08f40b798.png">
Updated

2022-09-25 05:59 UTC, jesec requested changes

2022-09-25 05:59 UTC, jesec commented on .github/workflows/ci.yml
> +        node-version: [12, 14, 16, 18]
No need for this change. Otherwise LG2M.

2022-09-27 07:11 UTC, robertsLando approved these changes

2023-02-27 06:50 UTC, ignatiusmb commented
What's left to do?

2023-02-27 11:16 UTC, robertsLando approved these changes

2023-03-20 10:05 UTC, robertsLando commented
@ignatiusmb Could you sync this with main branch please?

2023-03-28 06:19 UTC, robertsLando approved these changes

2023-03-28 06:21 UTC, robertsLando commented
Unfortunately I cannot merge this as there is Jesec review peding and I cannot dismiss it anyway... The only one who can is @leerob or we could simply close and reopen the pr

2023-03-28 08:06 UTC, baparham commented
> Unfortunately I cannot merge this as there is Jesec review peding and I cannot dismiss it anyway... The only one who can is @leerob or we could simply close and reopen the pr

I was able to dismiss it

2023-07-02 00:29 UTC, closed without merging