Ignore pnpm test for node14
vercel/pkg pull request #1919
Opened 2023-04-21 07:37 UTC by emmansun

according error message of the actions and https://github.com/pnpm/pnpm/issues/6297

2023-04-21 07:55 UTC, robertsLando requested changes

2023-04-21 07:55 UTC, robertsLando commented on test/utils.js
> +  const REQUIRED_MAJOR_VERSION = 16;
Shouldn't we check also pnpm version in this check? older pnpm versions also support older node versions

2023-04-21 08:29 UTC, emmansun commented
ok, close first.

2023-04-21 11:39 UTC, robertsLando approved these changes

2023-04-28 02:58 UTC, justajwolf commented
@baparham this pr is ok，you think？

2023-04-28 04:34 UTC, baparham approved these changes
Looks ok, I approved the workflow to run also, so if that passes this should be good to merge

2023-04-28 06:58 UTC, justajwolf commented
@emmansun It is time to merge this pr.

2023-04-28 07:01 UTC, baparham commented
> @emmansun It is time to merge this pr.

I believe the controls are setup so that it's on us to do that, but yes, time to merge.

2023-04-28 07:02 UTC, merged