Add pkg.outputPath
vercel/pkg pull request #574
Opened 2018-11-23 18:56 UTC by Symbitic

This adds a `pkg.outputPath` setting inside `package.json`. When given, output files will always be placed in this directory. It's identical to passing `--out-path` to the command-line.

I made this because it seems like the sort of thing people would want to specify in a configuration file, instead of needing to pass it to the command-line every time.
I also updated the README to explain how to use it, and I also added instructions about `pkg.targets`.

I'm relatively new to Git (and especially GitHub pull requests), so let me know if I did anything wrong.

2018-12-13 21:52 UTC, rauchg commented
Would you mind adding tests @Symbitic ? Then we can merge it

2018-12-26 14:39 UTC, Symbitic commented
I submitted a test. Do you know when it can be merged?

2021-03-26 08:44 UTC, robertsLando requested changes

2021-03-26 08:44 UTC, robertsLando commented on README.md
> -```
Please restore this lines

2021-03-26 08:49 UTC, robertsLando commented
@leerob this can be merged once tests pass

2021-03-26 14:28 UTC, leerob commented
The satisfaction merging this multiple year old PR
![](https://media.giphy.com/media/4PT6v3PQKG6Yg/giphy.gif)

2021-03-26 14:29 UTC, leerob approved these changes

2021-03-26 14:29 UTC, merged