promisified exec and execFile should return a promise with ChildProcess instance attached
vercel/pkg pull request #880
Opened 2020-03-30 12:36 UTC by onip

as per [documentation](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) `require('child_process').exec` and `require('child_process').execFile` should return a promise with attached a the `require('child_process').ChildProcess` instance attached to the `.child` property.

this PR is an adaption of the same code used inside nodejs

```
> require('child_process').exec[require('util').promisify.custom].toString ()
'(...args) => {\n' +
  '    let resolve;\n' +
  '    let reject;\n' +
  '    const promise = new Promise((res, rej) => {\n' +
  '      resolve = res;\n' +
  '      reject = rej;\n' +
  '    });\n' +
  '\n' +
  '    promise.child = orig(...args, (err, stdout, stderr) => {\n' +
  '      if (err !== null) {\n' +
  '        err.stdout = stdout;\n' +
  '        err.stderr = stderr;\n' +
  '        reject(err);\n' +
  '      } else {\n' +
  '        resolve({ stdout, stderr });\n' +
  '      }\n' +
  '    });\n' +
  '\n' +
  '    return promise;\n' +
  '  }'
```

2020-03-30 12:42 UTC, onip commented
resolves #881

2021-03-26 08:52 UTC, robertsLando commented
@onip Could you fix conflicts please? This is ok to merge once conflicts are fixed and tests pass @leerob

2021-03-26 11:23 UTC, onip commented
`master` merged in

2021-03-26 13:12 UTC, robertsLando requested changes

2021-03-26 13:12 UTC, robertsLando commented on prelude/bootstrap.js
> +      let resolve, reject;
```suggestion
      let resolve;
      let reject;
```

2021-03-26 14:04 UTC, robertsLando approved these changes
LGTM. @leerob merge this when possible please

2021-03-26 14:19 UTC, merged